#!/usr/bin/sh
#set -x

execDir=`dirname $0`
prog=`basename $0 .sh`

Help()
{
	echo "${prog} 1.0"
	echo "Copyright (c) 2005 Gras Savoye. All Rights Reserved"
	echo
	echo "Usage: [OPTION]"
	echo "-ipdf  Pdf form  input  file"
	echo "-ifdf  Fdf       input  file"
	echo "-opdf  Pdf       output file"
	echo "-log             log    file"
	echo "-?     Help"
	exit -1
}



#=================
# Main Entry Point
#=================
nbarg=$#
i=0
log="/dev/null"

if [ "$nbarg" -lt "1" ]
then
	Help
fi

while [ "$i" -lt "$nbarg" ]
do
	argv=$1
	shift
	i=`expr $i + 1`

	case ${argv} in
		-ipdf) #input pdf form file
			ipdf="${1}"
			shift
			i=`expr $i + 1`
			;;
		-ifdf) #input fdf file
			ifdf="${1}"
			shift
			i=`expr $i + 1`
			;;
		-opdf) #output pdf file
			opdf="${1}"
			shift
			i=`expr $i + 1`
			;;
		-log) #log file
			log=${1}
			shift
			i=`expr $i + 1`
			;;
		*) #invalid option
			Help
			;;
	esac
done

if [ "${ipdf}" = "" ] || [ "${ifdf}" = "" ] || [ "${opdf}" = "" ]
then
	echo "Erreur : -ipdf, -ifdf et -opdf sont obligatoires" >&2
	Help
fi

execline="${execDir}/pdftk/bin/pdftk ${ipdf} fill_form ${ifdf} output ${opdf} flatten"

${execline}
ret=$?

if [ "${ret}" != "0" ]
then
	rm -f "${opdf}"
fi

echo "exit code :$ret"
exit $ret
