#!/bin/sh

execDir=$(dirname "$0")
PDFTK="${execDir}/pdftk/bin/pdftk"

# Vérifier que pdftk existe
if [ ! -x "$PDFTK" ]; then
  echo "Erreur : pdftk introuvable ($PDFTK)" >&2
  echo "exit code :1"
  exit 1
fi

# Vérifier qu'au moins 1 argument est passé
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <arguments pdftk>" >&2
  echo "exit code :1"
  exit 1
fi

"$PDFTK" "$@"
ret=$?

echo "exit code :${ret}"
exit ${ret}
